In [1]:
import pandas as pd
import time
import random
from random import randrange
from datetime import timedelta
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

df_name = pd.read_csv('name.csv')  
tp = ['CPU','GPU']
cpu_list = ['AMD_Naples_Epyc ','AMD_Rome_Epyc','AMD_Milan_Epyc','Intel_Xeon','Intel_Itanium_2']
gpu_list = ['GeForce_RTX_3060','GeForce_RTX_3080','GeForce_RTX_3050','GeForce_RTX_3070','GeForce_RTX_3080','GeForce_GTX_1070','GeForce_GTX_1080','Nvidia_TITAN_X','Nvidia_TITAN_Xp','Nvidia_TITAN_V']

df_tenant = pd.DataFrame(data = {'ID': ['T0'], 'name': ['Albert'], 'deadline': ['2022-05-01 10:00:00'], 'type': ['CPU'], 'data_size_GB': [5], 'RAM_requirement_GB': [2], 'working_units': [300]})
df_provider = pd.DataFrame(data = {'ID': ['R0'], 'name': ['Adam'], 'available_start_time': ['2022-05-01 10:00:00'], 'available_end_time': ['2022-01-01 20:00:00'], 'type': ['CPU'], 'disk_size': [150], 'CPU_name': ['Intel_Xeon'], 'CPU_RAM_GB': [32], 'GPU_name': ['GeForce_RTX_3060'], 'GPU_RAM_GB': [4], 'working_units_per_hour': [30]})

In [2]:
def random_date(start, end):
    delta = end - start
    int_delta_hour = ((delta.days * 24 * 60 * 60) + delta.seconds)/3600
    random_hour = randrange(int_delta_hour)
    return start + timedelta(hours=random_hour)

d1 = datetime.strptime('2022-07-15 00:00:00', '%Y-%m-%d %H:%M:%S') #CHANGE
d2 = datetime.strptime('2022-08-01 00:00:00', '%Y-%m-%d %H:%M:%S')

d1_start = datetime.strptime('2022-07-01 00:00:00', '%Y-%m-%d %H:%M:%S') #CHANGE
d2_start = datetime.strptime('2022-07-10 00:00:00', '%Y-%m-%d %H:%M:%S')

random_date(d1, d2).strftime('%Y-%m-%d %H:%M:%S')

'2022-07-31 03:00:00'

In [3]:
for i in range(0,600): #CHANGE
    st_time = random_date(d1_start, d2_start)
    new_row_provider = {'ID': 'R'+str(i), 'name': df_name.loc[random.randint(200,399)][0], 'available_start_time': st_time.strftime('%Y-%m-%d %H:%M:%S'), 'available_end_time': (st_time + timedelta(hours=random.randint(50,650))).strftime('%Y-%m-%d %H:%M:%S'), 'type': tp[random.randint(0,1)], 'disk_size': random.randint(20,50)*5, 'CPU_name':cpu_list[random.randint(0,4)], 'CPU_RAM_GB': pow(2,random.randint(5,10)), 'GPU_name':gpu_list[random.randint(0,9)], 'GPU_RAM_GB': pow(2,random.randint(5,10)),'working_units_per_hour':random.randint(2,10)*5}
    df_provider = df_provider.append(new_row_provider,ignore_index=True)

for i in range(0,4500): #CHANGE
    new_row_tenant = {'ID': 'T'+str(i), 'name': df_name.loc[random.randint(0,199)][0], 'deadline': random_date(d1, d2).strftime('%Y-%m-%d %H:%M:%S'), 'type': tp[random.randint(0,1)], 'data_size_GB': random.randint(10,30)*5, 'RAM_requirement_GB': pow(2,random.randint(3,7)), 'working_units':random.randint(50,250)*5}
    df_tenant = df_tenant.append(new_row_tenant,ignore_index=True)

In [4]:
df_provider = df_provider.iloc[1: , :]
df_tenant = df_tenant.iloc[1: , :]

In [5]:
df_tenant

,ID,name,deadline,type,data_size_GB,RAM_requirement_GB,working_units
1,T0,Mary,2022-07-28 15:00:00,CPU,130,32,475
2,T1,Emma,2022-07-16 11:00:00,CPU,100,64,1035
3,T2,Amelia,2022-07-21 02:00:00,CPU,140,8,265
4,T3,Sabrina,2022-07-27 03:00:00,CPU,60,32,770
5,T4,Albert,2022-07-25 15:00:00,CPU,50,8,1185
...,...,...,...,...,...,...,...
4496,T4495,Honey,2022-07-26 23:00:00,CPU,75,32,280
4497,T4496,Natalie,2022-07-20 21:00:00,CPU,125,128,545
4498,T4497,Carlos,2022-07-29 08:00:00,CPU,85,128,625
4499,T4498,Maddie,2022-07-22 22:00:00,CPU,80,16,960
4500,T4499,Savana,2022-07-30 12:00:00,GPU,110,16,1180

In [6]:
df_provider

,ID,name,available_start_time,available_end_time,type,disk_size,CPU_name,CPU_RAM_GB,GPU_name,GPU_RAM_GB,working_units_per_hour
1,R0,Murphy,2022-07-05 23:00:00,2022-07-25 14:00:00,GPU,100,Intel_Itanium_2,128,GeForce_RTX_3050,256,15
2,R1,Cooper,2022-07-05 16:00:00,2022-07-12 20:00:00,CPU,150,AMD_Milan_Epyc,64,GeForce_RTX_3080,64,50
3,R2,Owens,2022-07-02 02:00:00,2022-07-16 21:00:00,CPU,100,Intel_Xeon,64,Nvidia_TITAN_X,256,10
4,R3,Watson,2022-07-04 22:00:00,2022-07-23 04:00:00,CPU,160,AMD_Naples_Epyc,1024,Nvidia_TITAN_V,128,20
5,R4,Holmes,2022-07-07 09:00:00,2022-07-22 06:00:00,GPU,105,AMD_Rome_Epyc,32,GeForce_GTX_1070,32,15
...,...,...,...,...,...,...,...,...,...,...,...
596,R595,Rogers,2022-07-07 07:00:00,2022-07-20 12:00:00,GPU,115,AMD_Rome_Epyc,256,GeForce_GTX_1080,32,25
597,R596,Kelly,2022-07-06 11:00:00,2022-07-19 13:00:00,CPU,195,AMD_Milan_Epyc,128,Nvidia_TITAN_V,1024,50
598,R597,Johnson,2022-07-09 21:00:00,2022-07-27 06:00:00,CPU,205,AMD_Milan_Epyc,1024,GeForce_RTX_3070,256,30
599,R598,Reed,2022-07-01 12:00:00,2022-07-25 19:00:00,GPU,175,Intel_Xeon,1024,GeForce_RTX_3080,1024,50
600,R599,Watson,2022-07-06 22:00:00,2022-07-27 07:00:00,GPU,190,AMD_Milan_Epyc,1024,GeForce_RTX_3050,256,25

In [24]:
df_tenant.to_csv('tenant_2022-07.csv', index=False) 
df_provider.to_csv('provider_2022-07.csv', index=False) 
#df_tenant.to_json('tenant_2022-05.json')
#df_provider.to_json('provider_2022-05.json')

In [57]:
import datetime
today = str(datetime.datetime.today()).split()[0]
today

'2022-06-09'

In [ ]:
df_tanant.to_csv('tanant_'+today+'.csv') 
df_renter.to_csv('renter_'+today+'.csv')